# Generated by Django 3.0.5 on 2020-04-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bb',
            old_name='publisher',
            new_name='published',
        ),
    ]
