# Generated by Django 3.0.5 on 2020-04-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_auto_20200429_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('spares', models.ManyToManyField(through='bboard.Kit', to='bboard.Spare')),
            ],
        ),
        migrations.AddField(
            model_name='kit',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.Machine'),
        ),
        migrations.AddField(
            model_name='kit',
            name='spare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.Spare'),
        ),
    ]
