# Generated by Django 3.0.5 on 2020-05-01 09:27

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to=bboard.models.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='MachineTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('spares', models.ManyToManyField(to='bboard.SpareTest')),
            ],
        ),
    ]
