# Generated by Django 3.0.5 on 2020-04-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicmodels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='spares',
        ),
        migrations.DeleteModel(
            name='AdvUser',
        ),
        migrations.DeleteModel(
            name='Bb',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
        migrations.DeleteModel(
            name='Spare',
        ),
    ]
